
cc_binary(
    name = "wasm",
    srcs = ["seclang.cpp"],
    deps = [
    	":t1"
    ],
    visibility = ["//visibility:public"]
)

cc_library(
    name = "t1",
    srcs = ["ttt/t1.cpp"],
    hdrs = ["ttt/t1.h"]
)